#ifndef SOURCE_FRONTEND_MAIN_MODULE_HPP
#define SOURCE_FRONTEND_MAIN_MODULE_HPP

#include <QAbstractListModel>
#include <QList>
#include <QtQml/qqml.h>

class MainModule : public QAbstractListModel
{
	Q_OBJECT
	QML_ELEMENT
	Q_PROPERTY(int size READ get_size  WRITE set_size  NOTIFY size_changed FINAL)

public:
	MainModule();

	// Functions generated by Qt for interacting with QML.
	auto rowCount(const QModelIndex &parent) const -> int override;
	auto data(const QModelIndex &index, int role) const -> QVariant override;
	auto removeRows(int row, int count, const QModelIndex &parent) -> bool override;
	auto roleNames() const -> QHash<int, QByteArray> override;

	auto get_size() const -> int;
	auto set_size(int new_size) -> void;

public slots:
	auto resize(int new_size) -> void;
	auto update_grid(int index, const QString& value) -> void;
	auto update_col_sum(int col, const QString& value) -> void;
	auto update_row_sum(int row, const QString& value) -> void;
	auto display_solution() -> void;

signals:
	auto size_changed() -> void;

private:
	QList<QString> m_grid_buffer; // Flattened grid.
	QList<QString> m_rows_sums;
	QList<QString> m_cols_sums;

	// QAbstractItemModel interface
	int m_size;

	auto check_input_validity() const -> bool;
};

#endif // SOURCE_FRONTEND_MAIN_MODULE_HPP
